spring.application.name=GoogleContacts

spring.security.user.name=user
spring.security.user.password=123

spring.security.oauth2.client.registration.google.client-id=771004981223-1ojl6ah3ffgdpe83q0t5vvb0pltgf420.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email, profile, https://www.googleapis.com/auth/contacts


logging.level.org.springframework.security=DEBUG